app/models/message.py
from app.extensions import db

class Message(db.Model):
    __tablename__ = 'messages'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    content = db.Column(db.Text, nullable=False)
    picture = db.Column(db.String(300))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    price = db.Column(db.String)
    link = db.Column(db.String(100))

    def __repr__(self):
        return f'<Message {self.title}>'

app/models/user.py
from app.extensions import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64),unique = True, index = True)
    username = db.Column(db.String(64),unique =True, index = True)
    password_hash = db.Column(db.String(128), nullable=False)
    messages = db.relationship('Message', backref='user')
    
    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

app/__init__.py
import os 
from flask import Flask 
from config import config
from app.extensions import db, migrate,login_manager

environment_config = os.getenv('ENVIRONMENT_CONFIG') or 'development'

def create_app(config_class=environment_config):
    print(config_class)
    app = Flask(__name__)
    app.config.from_object(config[config_class])
    # Initialize Flask extensions here
    db.init_app(app)
    migrate.init_app(app,db)
    login_manager.init_app(app)
    # Register blueprints here
    
    # auth blueprint
    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')
    # Memes blueprint
    from app.memes import bp as memes_bp
    app.register_blueprint(memes_bp, url_prefix='/memes')
    # Main blueprint
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    # Message blueprint
    from app.messages import bp as messages_bp
    app. register_blueprint(messages_bp,url_prefix='/messages')
    

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template
from app.models.message import Message

@bp.route('/')
def index():
    messages = Message.query.all()
    return render_template('index.html', messages = messages )
    

@bp.app_errorhandler(404)
def page_not_found(error):
        return render_template('page_not_found.html'), 404

app/memes/__init__.py
from flask import Blueprint
bp = Blueprint('memes', __name__)
from app.memes import routes

app/memes/routes.py
from app.memes import bp
from flask import render_template
from flask_login import login_required

@bp.route('/')
@login_required
def index():
    return render_template('memes/index.html')

app/messages/__init__.py
from flask import Blueprint
bp = Blueprint('messages',__name__)
from app.messages import routes

app/messages/routes.py
from flask import render_template, request, redirect, url_for, flash
from app.extensions import db
from app.messages import bp
from app.models.message import Message
from flask_login import login_required, current_user
@bp.route('/')
@login_required
def index():
    messages = Message.query.filter_by(user = current_user)
    return render_template('messages/index.html', messages = messages)
@bp.route('/create', methods = ('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        picture = request.form['picture']
        price = request.form['price']
        link = request.form['link']
        if not title:
            flash('El título es obligatorio')
        elif not content:
            flash('El contenido es obligatorio')
        else:
            message = Message(title = title, content = content, picture = picture, user = current_user, price = price, link = link)
            db.session.add(message)
            db.session.commit()
            return redirect(url_for('messages.index'))
    return render_template('messages/create.html')
@bp.route('/<id>/update', methods = ('GET', 'POST'))
@login_required
def update(id):
    message = Message.query.filter_by(id=id).first()
    if request.method == 'POST':
        if message:
            message.title = request.form['title']
            message.content = request.form['content']
            message.picture = request.form['picture']
            message.price = request.form['price']
            message.link = request.form['link']
            db.session.commit()
            return redirect('/')
            
    return render_template('messages/update.html', message =message)
    
@bp.route('/delete', methods = ['POST'])
def delete():
    id = request.form['id']
    message = Message.query.filter_by(id=id).first()
    db.session.delete(message)
    db.session.commit()
    flash('Mensaje Eliminado')
    return redirect('/')

app/templates/base.html
<!doctype html>
<html lang="es" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Bootstrap App - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{{  url_for('static', filename='styles.css')}}">
  </head>
  <body class="d-flex flex-column h-100">
    {% include 'includes/navbar.html' %}
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
        <div class="container mt-5">
      {% block body %}
      {% endblock %}
    </div>
    {% include 'includes/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/templates/includes/navbar.html
<nav class="navbar bg-light navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo" height="24"
        class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li xlass="nav-item">
          <a class="nav-link" href="{{url_for('main.index')}}">Inicio</a>
        </li>
        <li class="nav-item">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <a class="nav-link" aria-current="page" href="{{ url_for('auth.logout') }}">Salir</a>
          {% else %}
          <a class="nav-link" aria-current="page" href="{{ url_for('auth.login') }}">Ingreso</a>
          {% endif %}
        </li>
        <a class="nav-link" href="{{url_for('messages.index')}}">Mis mensajes</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/index.html
{% extends 'base.html' %}
{% block title %} User page {% endblock %}
{% block body %}
<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <h1>Mis Productos</h1>
    <a href="{{ url_for('messages.create')}}" class = 'btn btn-primary'>Nuevo</a>
    {% for message in messages %}
    {% if loop.index0 % 3 == 0 %}
  <div class="row">
    {% endif %}
      <div class="col">
        <div class='card m-3' >
            <img src="{{ message['picture']}}" class = 'card-img-top' alt="{{ message['title']}}"  >
            <div class="card-body">
            <h3 class="card-title">{{ message['title'] }}</h3>
            <p class="card-text">{{ message['content'] }}</p>
            {% if message['price'] %}
            <h3 class="card-title">{{ "${:}".format(message['price']) }}</h3>
            {% endif %}
            {% if message.user == current_user %}
            <a href="{{ url_for('messages.update', id = message.id)}}" class="btn btn-warning">Actualizar</a>
            <form action="{{url_for('messages.delete')}}" method="post" onsubmit ="return confirm('Estás seguro?')" class="d-inline">
              <input type="hidden" name="id" value="{{message.id}}">
              <input type="submit" value="Eliminar" class="btn btn-danger">
            </form>
            {% elif message['link'] != 'None' %}
            <a href="{{message['link']}}" class="btn btn-primary">comprar</a>
            {% endif %}
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}







  

app/templates/messages/create.html
{% extends 'base.html' %}
{% block title %} User page {% endblock %}
{% block body %}
<h1>Agrega un nuevo Producto</h1>
<form method = "POST">
    <label for = "títle" class = "form-label">Título</label>
    <input type = "text" name = "title" id = "title"
           placeholder = "Título del Mensaje "
           value = "{{ request.form['title'] }}" class = "form-control"></input>
    <label for = "picture" class = "form-label">Foto del producto</label>
    <input type = "text" name = "picture" id = "picture"
           placeholder = "Agrega tu Foto "
           value = "{{ request.form['picture'] }}" class = "form-control"></input>
    <label for = "content" class = "form-label">Contenido del Mensaje</label>
    <textarea name = "content" id = "content"
              placeholder = "Agrega el Mensaje"
              rows = "15"
              cols = "60"
              class = "form-control"
              >{{ request.form['content'] }}</textarea>
    <label for="price">Precio</label>
    <input type="text" name="price" id="price" class="form-control">
    <label for="price">link</label>
    <input type="text" name="link" id="price" class="form-control">
    <button type = "submit" class = "btn btn-primary mt-3">Submit</button>
</form>
{% endblock %}

app/templates/messages/index.html
{% extends 'base.html' %}

{% block title %} User page {% endblock %}

{% block body %}
<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <h1>Mensajes</h1>
    <a href="{{ url_for('messages.create')}}" class = 'btn btn-primary'>Nuevo</a>

    {% for message in messages %}
    {% if loop.index0 % 3 == 0 %}
  <div class="row">
    {% endif %}

      <div class="col">  
        <div class='card m-3' >      
            <img src="{{ message['picture']}}" class = 'card-img-top' alt="{{ message['title']}}"  >
            <div class="card-body">          
            <h3 class="card-title">{{ message['title'] }}</h3>         
            <p class="card-text">{{ message['content'] }}</p>         
            <a href="{{ url_for('messages.update', id = message.id)}}" class="btn btn-warning">Actualizar</a>         
            <form action="{{url_for('messages.delete')}}" method="post" onsubmit ="return confirm('tai seguro?')" class="d-inline">
              <input type="hidden" name="id" value="{{message.id}}">
              <input type="submit" value="Eliminar" class="btn btn-danger">
            </form>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}    

app/templates/messages/update.html
{% extends 'base.html' %}

{% block title %} User page {% endblock %}

{% block body %}
<h1>actualiza el mensaje</h1>
<form method="post">
    <label for="title">Titulo</label>
    <br>
    <input type="text" name="title" id="title"
           placeholder="Titulo del mensaje"
           value="{{message.title }}"></input>
    <br>

    <label for="picture">Foto</label>
    <br>
    <input type="text" name="picture" id="picturee"
           placeholder="Agrega tu Foto"
           value="{{message.picture }}"></input>
    <br>

    <label for="content">Contenido del mensaje</label>
    <br>
    <textarea name="content" id="content"
              placeholder="Contenido del mensaje"
              rows="15"
              cols="60"
              >{{message.content }}</textarea>
    <br>
    <button type="submit">Submit</button>
</form>
{% endblock %}

app/templates/page_not_found.html
{% extends 'base.html' %}
{% block title %} Pagina no encontrada {% endblock %}
{% block body %}
  <h1>
    lo sentimos pagina no existe
  </h1>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}

{% block title %} User page {% endblock %}

{% block body %}
<h1>{% if name%}
    Hello {{ name}} !
  {% else %}
    hello, stranger
  {% endif %}
</h1>
{% endblock %}

templates/includes/index.html
{% extends 'base.html' %}
{% block title %} User page {% endblock %}
{% block body %}
<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <h1>Aplicación Web con Flask y Bootstrap</h1>
    <a href="{{ url_for('create')}}" class="btn btn-primary">nuevo mensaje</a>
    {% for message in messages %}
        <div class='message'>
            <h3>{{ message['title'] }}</h3>
            <img src="{{message['picture']}}" alt="{{message['title']}}" class="img img-fluid">
            <p>{{ message['content'] }}</p>
            <a href="{{url_for('update', id = message.id)}}">actualizar</a>
            <form action="{{url_for('delete')}}" method="post" consubmit="return confirm ('Estas seguro?')">
              <input type="hidden" name="id" value="{{message.id}}">
              <input type="submit" value="Eliminar" class="btn btn-danger">
              </form>
        </div>
    {% endfor %}
      </div>
</main>
{% endblock %}







  